#ifndef SYSVER_HPP
#define SYSVER_HPP

#include <iostream>
#include "buildver.hpp"

//OS_VERSION for HSMS
//#define EQ_OS_VERSION					"2024_05_17"
#define EQ_OS_VERSION					"2024_07_25"

//ATMAIN
#define ATMAIN_NAME					"atmain"
#define ATMAIN_VER					"v1.0.1"
#define ATMAIN_DATE					EQ_OS_VERSION

//ATMGR
#define ATMGR_NAME					"atmgr"
#define ATMGR_VER					"v1.0.1"
#define ATMGR_DATE					EQ_OS_VERSION

//TESTLIB
#define TESTLIB_NAME				"testlib"
#define TESTLIB_VER					"v1.0.0"
#define TESTLIB_DATE				"2024/06/24 - NRZC_S1PS"	//2024.06.24 - KWMOON

//ATLOADER
#define ATLOADER_NAME				"atloader"
#define ATLOADER_VER				"v1.0.1"
#define ATLOADER_DATE				"2024/06/17"

//ATCL
#define ATCL_NAME					"atcl"
#define ATCL_VER					"v1.0.0"
#define ATCL_DATE					EQ_OS_VERSION

//ATCALDIAG
#define ATCALDIAG_NAME				"atdiag"
#define ATCALDIAG_VER				"v1.0.0"
#define ATCALDIAG_DATE				EQ_OS_VERSION

//ATCHAMBER UI
#define ATCHMBUI_NAME				"atchmbui"
#define ATCHMBUI_VER				"v1.0.0"
#define ATCHMBUI_DATE				EQ_OS_VERSION

//ATCHAMBER COMMUNICATION
#define ATCHMBCOMM_NAME				"atchmbcomm"
#define ATCHMBCOMM_VER				"v1.0.0"
#define ATCHMBCOMM_DATE				EQ_OS_VERSION

//ATCHAMBER COMMUNICATION
#define ATSYSMONUI_NAME				"atsysmonui"
#define ATSYSMONUI_VER				"v1.0.0"
#define ATSYSMONUI_DATE				EQ_OS_VERSION

//ATCHAMBER COMMUNICATION
#define ATSETUPUI_NAME				"atsetup"
#define ATSETUPUI_VER				"v1.0.0"
#define ATSETUPUI_DATE				EQ_OS_VERSION

#define ATIO_NAME					"atio"
#define ATIO_VER					"v1.0.0"
#define ATIO_DATE					"2023/09/15"

#define ATSAVEDATA_NAME				"atsavedata"
#define ATSAVEDATA_VER				"v1.0.0"
#define ATSAVEDATA_DATE				EQ_OS_VERSION

#define ATSAVEMAP_NAME				"atsavemap"
#define ATSAVEMAP_VER				"v1.0.0"
#define ATSAVEMAP_DATE				EQ_OS_VERSION

//ATLOGVIEWER MAIN UI
#define ATLOGVIEWUI_NAME			"atlogviewer"
#define ATLOGVIEWUI_VER				"v1.0.0"
#define ATLOGVIEWUI_DATE			EQ_OS_VERSION

//ATTMS MAIN UI
#define ATTMSUI_NAME				"attmsui"
#define ATTMSUI_VER					"v1.0.0"
#define ATTMSUI_DATE				EQ_OS_VERSION

//ATEAP SIMM
#define ATEAPSIMM_NAME				"ateapsimm"
#define ATEAPSIMM_VER				"v1.0.0"
#define ATEAPSIMM_DATE				EQ_OS_VERSION

//ATEAP SIMM
#define ATPLCSIMMUI_NAME			"atplcsimm"
#define ATPLCSIMMUI_VER				"v1.0.0"
#define ATPLCSIMMUI_DATE			EQ_OS_VERSION

#define ATMAIN_VERSION				ATMAIN_NAME " " ATMAIN_VER "[" ATMAIN_DATE "]"
#define ATMGR_VERSION				ATMGR_NAME " " ATMGR_VER "[" ATMGR_DATE "]"
#define TESTLIB_VERSION				TESTLIB_NAME " " TESTLIB_VER"[" TESTLIB_DATE "]"
#define ATLOADER_VERSION			ATLOADER_NAME " " ATLOADER_VER "[" ATLOADER_DATE "]"
#define ATCL_VERSION				ATCL_NAME " " ATCL_VER "[" ATCL_DATE "]"
#define ATCALDIAG_VERSION			ATCALDIAG_NAME " " ATCALDIAG_VER "[" ATCALDIAG_DATE "]"
#define ATCHMBUI_VERSION			ATCHMBUI_NAME " " ATCHMBUI_VER "[" ATCHMBUI_DATE "]"
#define ATCHMBCOMM_VERSION			ATCHMBCOMM_NAME " " ATCHMBCOMM_VER "[" ATCHMBCOMM_DATE "]"
#define ATSETUP_VERSION				ATSETUPUI_NAME " " ATSETUPUI_VER "[" ATSETUPUI_DATE "]"
#define ATLOGVIEWER_VERSION			ATLOGVIEWUI_NAME " " ATLOGVIEWUI_VER "[" ATLOGVIEWUI_DATE "]"
#define ATTMSUI_VERSION				ATTMSUI_NAME " " ATTMSUI_VER "[" ATTMSUI_DATE "]"
#define ATEAPSIMM_VERSION			ATEAPSIMM_NAME " " ATEAPSIMM_VER "[" ATEAPSIMM_DATE "]"

#define RC_SOV						"__ABLEE_SOV__,"
#define RC_EOV						",__ABLEE_EOV__"

#define RC_ATMAIN_VERSION			RC_SOV ATMAIN_VERSION		RC_EOV
#define RC_ATMGR_VERSION			RC_SOV ATMGR_VERSION		RC_EOV
#define RC_TESTLIB_VERSION			RC_SOV TESTLIB_VERSION		RC_EOV
#define RC_ATLOADER_VERSION			RC_SOV ATLOADER_VERSION		RC_EOV
#define RC_ATCL_VERSION				RC_SOV ATCL_VERSION			RC_EOV
#define RC_ATCALDIAG_VERSION		RC_SOV ATCALDIAG_VERSION	RC_EOV
#define RC_ATCHMBUI_VERSION			RC_SOV ATCHMBUI_VERSION		RC_EOV
#define RC_ATCHMBCOMM_VERSION		RC_SOV ATCHMBCOMM_VERSION	RC_EOV
#define RC_ATSETUP_VERSION			RC_SOV ATSETUP_VERSION		RC_EOV
#define RC_ATLOGVIEWER_VERSION		RC_SOV ATLOGVIEWER_VERSION	RC_EOV
#define RC_ATTMSUI_VERSION			RC_SOV ATTMSUI_VERSION    	RC_EOV
#define RC_ATEAPSIMM_VERSION		RC_SOV ATEAPSIMM_VERSION   	RC_EOV

#endif
